networks:
  claude-platform:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
services:
  ccflare-monitor:
    container_name: ccflare_monitor
    environment:
    - MONITORING_MODE=multi_agent
    - AGENTS_TO_MONITOR=all
    - TOKEN_BUDGET_TOTAL=93000
    - CONTEXT7_TRACKING=enabled
    image: ccflare-dashboard:latest
    networks:
    - claude-platform
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./monitoring-data:/data
    - ./shared-memory:/shared
  conport-agent:
    container_name: conport_agent
    environment:
    - AGENT_ROLE=project_memory
    - MCP_SERVERS=conport
    - TOKEN_BUDGET=8000
    - PRIORITY=1
    image: claude-code-coordination:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/conport:/config
    - ./shared-memory:/shared
    - ./conport-data:/conport-storage
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  context7-agent:
    container_name: context7_agent
    environment:
    - AGENT_ROLE=context7_primary
    - MCP_SERVERS=context7
    - TOKEN_BUDGET=8000
    - PRIORITY=1
    - MANDATORY_FOR=code_analysis,code_generation,api_documentation
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/health
      timeout: 10s
    image: claude-code-research:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/context7:/config
    - ./shared-memory:/shared
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  crystal-orchestrator:
    container_name: crystal_orchestrator
    depends_on:
    - context7-agent
    - conport-agent
    environment:
    - ORCHESTRATION_MODE=platform_evolution
    - AGENTS_CONFIG_PATH=/config/agents.yaml
    - CONTEXT7_PRIORITY=highest
    image: stravu/crystal:latest
    networks:
    - claude-platform
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - ./platform-evolution:/config
    - ./shared-memory:/shared
    - /var/run/docker.sock:/var/run/docker.sock
  exa-agent:
    container_name: exa_agent
    depends_on:
    - context7-agent
    environment:
    - AGENT_ROLE=web_research
    - MCP_SERVERS=exa
    - TOKEN_BUDGET=10000
    - PRIORITY=2
    - DEPENDS_ON=context7_agent
    image: claude-code-research:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/exa:/config
    - ./shared-memory:/shared
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  openmemory-agent:
    container_name: openmemory_agent
    environment:
    - AGENT_ROLE=personal_memory
    - MCP_SERVERS=openmemory
    - TOKEN_BUDGET=5000
    - PRIORITY=2
    image: claude-code-coordination:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/openmemory:/config
    - ./shared-memory:/shared
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  serena-agent:
    container_name: serena_agent
    depends_on:
    - context7-agent
    environment:
    - AGENT_ROLE=code_implementation
    - MCP_SERVERS=serena,context7
    - TOKEN_BUDGET=15000
    - PRIORITY=1
    - PRE_ACTION_REQUIREMENT=query_context7_first
    - CONTEXT7_MANDATORY=true
    image: claude-code-implementation:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/serena:/config
    - ./shared-memory:/shared
    - ./codebase:/workspace
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  taskmaster-agent:
    container_name: taskmaster_agent
    depends_on:
    - context7-agent
    environment:
    - AGENT_ROLE=task_management
    - MCP_SERVERS=task-master-ai,context7
    - TOKEN_BUDGET=12000
    - PRIORITY=2
    - CONTEXT7_INTEGRATION=enabled
    image: claude-code-implementation:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/taskmaster:/config
    - ./shared-memory:/shared
    - ./.taskmaster:/taskmaster-data
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  testing-agent:
    container_name: testing_agent
    depends_on:
    - context7-agent
    environment:
    - AGENT_ROLE=test_generation
    - MCP_SERVERS=context7
    - TOKEN_BUDGET=8000
    - PRIORITY=2
    - CONTEXT7_FOCUS=testing_frameworks
    image: claude-code-quality:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/testing:/config
    - ./shared-memory:/shared
    - ./tests:/test-workspace
    - ./mcp-coordination_cluster.json:/app/mcp-config.json:ro
  zen-reviewer:
    container_name: zen_reviewer
    depends_on:
    - context7-agent
    environment:
    - AGENT_ROLE=code_review
    - MCP_SERVERS=zen,context7
    - TOKEN_BUDGET=15000
    - PRIORITY=1
    - CONTEXT7_REQUIREMENT=reference_official_docs
    image: claude-code-quality:latest
    networks:
    - claude-platform
    restart: unless-stopped
    volumes:
    - ./agent-configs/zen:/config
    - ./shared-memory:/shared
version: '3.8'
volumes:
  conport-data:
    driver: local
  monitoring-data:
    driver: local
  shared-memory:
    driver: local
x-healthcheck-defaults:
  interval: 30s
  retries: 3
  start_period: 40s
  timeout: 10s
