version: '3.8'

services:
  gptr-mcp:
    image: gptresearcher/gptr-mcp:latest
    container_name: dopemux-gptr-mcp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - RETRIEVER=tavily
      - GPTR_LOG_LEVEL=INFO
      - DOC_PATH=/app/docs
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Redis for caching research results
  redis:
    image: redis:7-alpine
    container_name: dopemux-research-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: