# MetaMCP Policy Configuration
# Simple policy for initial testing
version: "1.0"
policies:
  access_control:
    enabled: true
    default_action: "allow"
    rules: []

  rate_limiting:
    enabled: false
    default_limit: 100
    rules: []

  resource_limits:
    max_concurrent_requests: 10
    max_request_size: "10MB"
    request_timeout: 30

  security:
    authentication_required: false
    authorization_enabled: false
    audit_enabled: true

  quality_of_service:
    priority_levels:
      high: 1
      normal: 2
      low: 3
    default_priority: "normal"
