name: docs
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install pre-commit
      - run: pre-commit run -a
      - name: Broken-link check (lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config .lychee.toml docs/**/*.md
